server:
  port: 8080

spring:
  application:
    name: banking-transaction-management
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: update
          create_namespaces: true
          format_sql: true
          jdbc:
            batch_size: 50
        jdbc:
          batch_size: 50
        jdbc_time_zone: UTC
        show_sql: true
        format_sql: true
app:
  jwtSecret: d81d5519-12ed-4aab-a385-a060520c0474
  jwtExpirationMs: 3600000